#!/usr/bin/env Rscript
suppressPackageStartupMessages(library(RSienaTest))
suppressPackageStartupMessages(library(tcltk))
RSienaTest:::DONE(FALSE)
siena01Gui()
while(!RSienaTest:::DONE()) {Sys.sleep(0.1)}

